- id: latexindent
  name: latexindent.pl
  description: Run latexindent.pl (get dependencies using CPAN)
  minimum_pre_commit_version: 2.1.0
  entry: bash -xc 'echo "$@" | xargs --verbose -n1 latexindent.pl' --
  language: perl
  types: [tex]
- id: latexindent-conda
  name: latexindent.pl
  description: Run latexindent.pl (get dependencies using Conda)
  minimum_pre_commit_version: 2.1.0
  entry: bash -xc 'echo "$@" | xargs --verbose -n1 latexindent.pl' --
  language: conda
  types: [tex]
